old_sound_rabbit_mq:
  connections:
    default:
      host: '%env(resolve:RABBITMQ_HOST)%'
      port: '%env(resolve:RABBITMQ_PORT)%'
      user: '%env(resolve:RABBITMQ_USER)%'
      password: '%env(resolve:RABBITMQ_PASSWORD)%'
      vhost: '%env(resolve:RABBITMQ_VHOST)%'
  producers:
    transaction:
      connection: default
      exchange_options: {name: 'transaction-producer', type: direct}
  consumers:
    credit_create:
      connection: default
      queue_options: {name: 'credit-queue'}
      callback: App\MessageBroker\CreditCreateConsumer
    debit_create:
      connection: default
      queue_options: {name: 'debit-queue'}
      callback: App\MessageBroker\DebitCreateConsumer
    transfer_create:
      connection: default
      queue_options: {name: 'transfer-queue'}
      callback: App\MessageBroker\TransferCreateConsumer
    transaction_update:
      connection: default
      queue_options: {name: 'transaction-update'}
      callback: App\MessageBroker\TransactionUpdateConsumer
