version: '3'

services:
  db_transactions:
    image: postgres:9.6-alpine
    environment:
    - POSTGRES_DB=db_transactions
    - POSTGRES_USER=user
    - POSTGRES_PASSWORD=PwD34451DeV
    ports:
    - 8811:5432

  php_transactions:
    build: docker/php
    container_name: php_transactions
    restart: always
    tty: true
    volumes:
    - .:/srv/transactions:delegated
    ports:
    - 8812:9000
    - 8813:9001
  rabbitMq:
    image: rabbitmq:3-management
    ports:
    - 8810:15672
    - 8814:5672
    - 8815:5671
    environment:
      RABBITMQ_DEFAULT_PASS: pass
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_VHOST: vhost